version: '3.7'

services:
  db:
    image: postgres:11.4
    environment:
      POSTGRES_USER: galaxy
      POSTGRES_PASSWORD: galaxy
      POSTGRES_DB: galaxy
    ports:
      - "54320:5432"
    volumes:
      - "./data/sql:/docker-entrypoint-initdb.d"