"""empty message

Revision ID: 2ec47ac1328f
Revises: 47104fa9b791
Create Date: 2019-10-19 13:40:04.440890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec47ac1328f'
down_revision = '47104fa9b791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_namespaces', 'name',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_index('ix_provider_namespaces_name', table_name='provider_namespaces')
    op.create_index(op.f('ix_provider_namespaces_name'), 'provider_namespaces', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_namespaces_name'), table_name='provider_namespaces')
    op.create_index('ix_provider_namespaces_name', 'provider_namespaces', ['name'], unique=True)
    op.alter_column('provider_namespaces', 'name',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
