"""empty message

Revision ID: 47104fa9b791
Revises: 54597e4bfe5b
Create Date: 2019-10-17 19:49:38.490001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47104fa9b791'
down_revision = '54597e4bfe5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('provider_namespaces_provider_id_namespace_id_key', 'provider_namespaces', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('provider_namespaces_provider_id_namespace_id_key', 'provider_namespaces', ['provider_id', 'namespace_id'])
    # ### end Alembic commands ###
