"""empty message

Revision ID: 54597e4bfe5b
Revises: 2b4474384de3
Create Date: 2019-10-17 19:27:07.741080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54597e4bfe5b'
down_revision = '2b4474384de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('platforms_name_release_key', 'platforms', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('platforms_name_release_key', 'platforms', ['name', 'release'])
    # ### end Alembic commands ###
