"""empty message

Revision ID: c234cb41fce4
Revises: 6fe6cf3d45e2
Create Date: 2019-10-23 10:05:35.614303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c234cb41fce4'
down_revision = '6fe6cf3d45e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_name_namespace_id_key', 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['name', 'namespace_id', 'repository_id', 'role_type_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint('roles_name_namespace_id_key', 'roles', ['name', 'namespace_id'])
    # ### end Alembic commands ###
