"""Add active column on ProviderNamespace

Revision ID: fbafc079b445
Revises: 03f7a2e98c96
Create Date: 2019-08-18 16:00:45.740015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbafc079b445'
down_revision = '03f7a2e98c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_namespaces', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_namespaces', 'is_active')
    # ### end Alembic commands ###
